name: Run Koyeb Auto Login

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # 每周一 UTC 00:00
  push:
    branches:
      - main

jobs:
  login-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 1. 拉取仓库代码
        uses: actions/checkout@v4

      - name: 2. 配置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: 3. 执行 API 保活
        env:
          TEL_TOK: ${{ secrets.TEL_TOK }}
          TEL_ID: ${{ secrets.TEL_ID }}
          KOY_TOKENS: ${{ secrets.KOY_TOKENS }}
          KOY_ACC: ${{ secrets.KOY_ACC }}
        run: python koyeb-login.py

      - name: 4. 更新仓库活跃度 (time.txt)
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "Last run: $(date +'%Y-%m-%d %H:%M:%S')" > time.txt
          git add time.txt
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "chore: auto update active log $(date +'%Y-%m-%d %H:%M:%S')"
            git push origin HEAD:main
          fi
